### ISSUE TITLE
0.4.1 "View on userscripts.org" not working

### ISSUE THREAD

**Issue by hurda** [LouCypher/AM_contextmenu#2]
AMC 0.4.1, Greasemonkey 1.12, Firefox 24.

Clicking on "View on userscripts.org" for a userscript causes the following error:

```
NS_ERROR_MALFORMED_URI: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService2.newURI] @ chrome://global/content/contentAreaUtils.js:782
```

The same operation is working fine with AMC 0.4

**Comment by hurda** [comment]
And with 0.4.1, a right-click on a plugin (Flash) now shows an entry called "Visit Add-on support", which doesn't work (throws the same error) and which didn't exist in 0.4.

**Comment by LouCypher** [comment]
Thank you for your report. Please try the updated version
https://addons.mozilla.org/addon/am-context/versions/0.4.2

**Comment by hurda** [comment]
It's working, thank you.
