### ISSUE TITLE
Language translations

### ISSUE THREAD

**Issue by HrantOhanyan** [LouCypher/AM_contextmenu#3]
Hi
I've translated into Armenian the extension Add-ons Manager Context Menu (on Babelzilla), can you include my translation in Add-ons Manager Context Menu addon?
Thanks.

**Comment by LouCypher** [comment]
Hi
I have downloaded [your tanslation](http://www.babelzilla.org/index.php?option=com_wts&Itemid=88&language=64&extension=5652&type=filelist2) and will include it on the next release.
Thank you for your contribution.
:beers:

**Comment by LouCypher** [comment]
It looks good :+1: 

![hy-am](https://f.cloud.github.com/assets/42596/1426105/eb7a1de4-4059-11e3-91bd-4c0c48dcd714.png)
