### ISSUE TITLE
Visit Home Page - wrong in this example

### ISSUE THREAD

**Issue by LL25255252** [LouCypher/AM_contextmenu#6]
A qusetion about Add-ons Manager Context Menu :

Choosing "Visit Home Page" on the context-menu of BarTab Heavy addon opens

BarTab
https://addons.mozilla.org/en-US/firefox/addon/bartab/

Instead of :

BarTab Heavy
https://addons.mozilla.org/en-US/firefox/addon/bartab-heavy/

TIA.

**Comment by jerone** [comment]
That's because they didn't change the `homepageURL` in the install.rdf when they forked the project. You need to contact the author of BarTab Heavy to fix this.

**Comment by LL25255252** [comment]
Thanks.

**Comment by LouCypher** [comment]
Thanks, @jerone.

@LL25255252, BarTab Heavy is on [GitHub](/inverseparadox/BarTab), but unfortunately they disable the [issues](/inverseparadox/BarTab/issues) page.

**Comment by LL25255252** [comment]
@LouCypher ,are you sure you just provided the link to Latest (3.2.1) version of BarTab Heavy on Github ?

**Comment by LouCypher** [comment]
See https://addons.mozilla.org/addon/bartab-heavy/#developer-comments

**Comment by LL25255252** [comment]
Sorry for posting again here even though there's no problem in AM_contextmenu...
I want to report the issue above to the dev of BarTab Heavy. The dev name on AMO is Hazon - https://addons.mozilla.org/en-US/firefox/user/Hazon/ but there's no email address to leave a bug report.
Can you help me find a way to contact that dev ?
